#ifndef PROTOCOL_H
#define PROTOCOL_H

#define DEFAULT_PORT 7777
#define LOCALHOST "127.0.0.1"
#define BUFFER_SIZE 1024

enum PACKAGE_TYPE {
    REQ_LIST = 1, REQ_GET = 2, REQ_PUT = 3, RES_END = 4, RES_FAILURE = 5, RES_FILE_PART = 6, RES_FILE_SIZE = 7, RES_LIST_ANSWER = 8
};

#endif / PROTOCOL_H */